In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MaxAbsScaler
from nltk.tokenize import word_tokenize
from nltk.tokenize import SpaceTokenizer 
import os
import psutil

In [2]:
data = pd.read_csv("888.csv")
x = data['Review']
y = data['Liked']
x

0                                          তিনি কাজ জানেন
1                                       তিনি কাজ জানেন না
2                                  তিনি কোনো কাজ জানেন না
3                                       তিনি কাজ করতে চান
4                                    তিনি কাজ করতে ভয় পান
5                             তিনি কাজ করতে অনেক ভালবাসেন
6                                  তিনি কাজ করতে ভালবাসেন
7                                       সবাই তাকে ভাল পান
8                                  সবাই তাকে অনেক ভাল পান
9                                      তার কাজ করতে পছন্দ
10                                  তার কাজ করতে পছন্দ না
11                                      তিনি সবার ভাল চান
12                                   তিনি কারো ভাল চান না
13                                   তিনি আমাকে মারতে চান
14                                 তিনি কারো খারাপ চান না
15                                      তিনি খারাপ চান না
16                             তিনি কারো ভাল দেখতে পান না
17            

In [3]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [4]:
stop_words=['অনেকে','অনেকেই','অথবা','অথচ','অর্থাত','অন্য','আজ','আপনার','আপনি','আবার','আমরা','আমাকে','আমাদের',
'আমার','আমি','আর','আই','আগামী','অবধি','আদ্যভাগে','এই','একই','একে','একটি','এটি','এটা','এটাই','এবং','একবার',
'এবার','এদের','এঁদের','এমন','এমনকী','এল','এর','এরা','এঁরা','এস','এত','এতে','এসে','একে','এ','ঐ','ই','ইহা','ইত্যাদি'
,'উনি','উপর','উপরে','ও','ওই','ওর','ওরা','ওঁর','ওঁরা','ওকে','ওদের','ওঁদের','ওখানে','কত','কবে','সেখানে','সে', 'স্বয়ং',
'কি','কী','তিনি','তিনঐ','তিনিও','তাঁদের','তাঁহারা','তাঁরা','তাঁর','তাঁকে','তাই','তাকে','তাহার','তাদের','তারা','তারৈ','তার','তিনি',
'তুমি','তোমার','তথা','দু','দুটি','দুটো','নিজে','নিজেই','নিজের','নিজেদের','প্রভৃতি','বার','বা','ভাবে','ভাবেই','মধ্যভাগে','যাকে',
'যার','যারা','যাঁর','যাঁরা','যাদের','যিনি','যে','সবার','সহ','সুতরাং', 'সহিত','সেই','সেটা','সেটি','সেটাই','সেটাও','সম্প্রতি','সেখান', 
'হিসাবে','জন','জনকে','জনের','জন্যওজে','জে','তুলে','মোট','টি']

In [5]:
import nltk

In [6]:
tokens=x
filtered=x
for i in range(len(x)):
    tokens= nltk.word_tokenize(x[i])
    filtered[i]= [w for w in tokens if not w in stop_words]

In [7]:
print(filtered)

0                                            [কাজ, জানেন]
1                                        [কাজ, জানেন, না]
2                                  [কোনো, কাজ, জানেন, না]
3                                        [কাজ, করতে, চান]
4                                    [কাজ, করতে, ভয়, পান]
5                             [কাজ, করতে, অনেক, ভালবাসেন]
6                                   [কাজ, করতে, ভালবাসেন]
7                                        [সবাই, ভাল, পান]
8                                  [সবাই, অনেক, ভাল, পান]
9                                      [কাজ, করতে, পছন্দ]
10                                 [কাজ, করতে, পছন্দ, না]
11                                             [ভাল, চান]
12                                   [কারো, ভাল, চান, না]
13                                           [মারতে, চান]
14                                 [কারো, খারাপ, চান, না]
15                                       [খারাপ, চান, না]
16                            [কারো, ভাল, দেখতে, পান, না]
17            

In [8]:
STR=x
for i in range(len(filtered)):
     STR[i] = ' '.join(filtered[i])

In [9]:
Initializing = TfidfVectorizer()
x_final = Initializing.fit_transform(STR)
a = x_final.toarray()

In [10]:
hello = preprocessing.LabelEncoder()
y_final = hello.fit_transform(y)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(a,y_final,test_size = 0.2, random_state =2)

In [12]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [13]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train)
prediction3 = rf.predict(x_test)


count3 = 0
for i in range (len(prediction3)):
    if(prediction3[i]==y_test[i]):
        count3=count3+1

print(count3)
print(len(prediction3))

print("Accuracy : ", (count3/len(prediction3))*100)
'''AccRF=accuracy_score(y_test,prediction3)*100'''
F1RF=f1_score(y_test,prediction3,average='weighted')*100
RRF=recall_score(y_test,prediction3,average='weighted')*100
PRF=precision_score(y_test,prediction3,average='weighted')*100

print('Confusion Matrix')
print(confusion_matrix(y_test, prediction3))

'''print("Accuracy : ",AccRF )'''

print ('f1 Score:',F1RF)

print ('Recall:',RRF)

print ('Precision:',PRF)

C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


1093
1492
Accuracy :  73.25737265415549
Confusion Matrix
[[577 185   0]
 [213 516   1]
 [  0   0   0]]
f1 Score: 73.26053815324154
Recall: 73.25737265415549
Precision: 73.31742726104741


C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [14]:
#Neural Network
from sklearn.neural_network import MLPClassifier
neural_network = MLPClassifier( hidden_layer_sizes=(200,250), activation='relu', solver='adam', alpha=0.2, batch_size='auto', learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=5000, shuffle=True, random_state=90, tol=0.001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.8, beta_2=0.8, epsilon=1e-08  )
neural_network.fit(x_train, y_train)
prediction4 = neural_network.predict(x_test)  
count4 = 0
for i in range (len(prediction4)):
    if(prediction4[i]==y_test[i]):
        count4=count4+1

print(count4)
print(len(prediction4))

print("Accuracy : ", (count4/len(prediction4))*100)
'''AccNN=accuracy_score(y_test,prediction1)*100'''
F1NN=f1_score(y_test,prediction4,average='weighted')*100
RNN=recall_score(y_test,prediction4,average='weighted')*100
PNN=precision_score(y_test,prediction4,average='weighted')*100

print('Confusion Matrix')
print(confusion_matrix(y_test, prediction4))

'''print("Accuracy : ",AccNN )'''

print ('f1 Score:',F1NN)

print ('Recall:',RNN)

print ('Precision:',PNN)

1073
1492
Accuracy :  71.91689008042896
Confusion Matrix
[[618 144]
 [275 455]]
f1 Score: 71.64425538650484
Recall: 71.91689008042896
Precision: 72.50999047410266


In [15]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
prediction6 = dt.predict(x_test)


count6 = 0
for i in range (len(prediction6)):
    if(prediction6[i]==y_test[i]):
        count6=count6+1

print(count6)
print(len(prediction6))
print("Accuracy : ", (count6/len(prediction6))*100)

'''AccDT=accuracy_score(y_test,prediction6)*100'''
F1DT=f1_score(y_test,prediction6,average='weighted')*100
RDT=recall_score(y_test,prediction6,average='weighted')*100
PDT=precision_score(y_test,prediction6,average='weighted')*100

print('Confusion Matrix')
print(confusion_matrix(y_test, prediction6))

'''print("Accuracy : ",AccDT )'''

print ('f1 Score:',F1DT)

print ('Recall:',RDT)

print ('Precision:',PDT)

1050
1492
Accuracy :  70.37533512064343
Confusion Matrix
[[516 246]
 [196 534]]
f1 Score: 70.3633560941662
Recall: 70.37533512064343
Precision: 70.50973095344575
