In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MaxAbsScaler
from nltk.tokenize import word_tokenize
from nltk.tokenize import SpaceTokenizer 
import os
import psutil

In [2]:
data = pd.read_csv("888.csv")

In [3]:
x = data['Review']
y = data['Liked']

In [4]:
Initializing = TfidfVectorizer()
x_final = Initializing.fit_transform(x)

In [5]:
a = x_final.toarray()
hello = preprocessing.LabelEncoder()
y_final = hello.fit_transform(y)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(a,y_final,test_size = 0.4, random_state = 2)

In [7]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [8]:
#Neural Network
from sklearn.neural_network import MLPClassifier
neural_network = MLPClassifier( hidden_layer_sizes=(200,250), activation='relu', solver='adam', alpha=0.2, batch_size='auto', learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=5000, shuffle=True, random_state=90, tol=0.001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True, early_stopping=False, validation_fraction=0.1, beta_1=0.8, beta_2=0.8, epsilon=1e-08  )
neural_network.fit(x_train, y_train)
prediction1 = neural_network.predict(x_test)  
count1 = 0
for i in range (len(prediction1)):
    if(prediction1[i]==y_test[i]):
        count1=count1+1

print(count1)
print(len(prediction1))

AccNN=accuracy_score(y_test,prediction1)*100
F1NN=f1_score(y_test,prediction1,average='weighted')*100
RNN=recall_score(y_test,prediction1,average='weighted')*100
PNN=precision_score(y_test,prediction1,average='weighted')*100

print('Confusion Matrix')
print(confusion_matrix(y_test, prediction1))

print("Accuracy : ",AccNN )

print ('f1 Score:',F1NN)

print ('Recall:',RNN)

print ('Precision:',PNN)

2088
2984
Confusion Matrix
[[   0    0    1    0    0]
 [   0    0    0    1    0]
 [   0    0 1158  356    0]
 [   0    0  537  930    0]
 [   0    0    0    1    0]]
Accuracy :  69.97319034852548
f1 Score: 69.79787559079386
Recall: 69.97319034852548
Precision: 70.14009333029408


C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [9]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train, y_train)
prediction3 = rf.predict(x_test)


count3 = 0
for i in range (len(prediction3)):
    if(prediction3[i]==y_test[i]):
        count3=count3+1

print(count3)
print(len(prediction3))

AccRF=accuracy_score(y_test,prediction3)*100
F1RF=f1_score(y_test,prediction3,average='weighted')*100
RRF=recall_score(y_test,prediction3,average='weighted')*100
PRF=precision_score(y_test,prediction3,average='weighted')*100

print('Confusion Matrix')
print(confusion_matrix(y_test, prediction3))

print("Accuracy : ",AccRF )

print ('f1 Score:',F1RF)

print ('Recall:',RRF)

print ('Precision:',PRF)

C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


2096
2984
Confusion Matrix
[[   0    0    0    1    0]
 [   0    0    0    1    0]
 [   0    0 1025  489    0]
 [   0    0  396 1071    0]
 [   0    0    0    1    0]]
Accuracy :  70.24128686327077
f1 Score: 70.19256139456313
Recall: 70.24128686327077
Precision: 70.28491454736606


C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [10]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
prediction5 = dt.predict(x_test)


count5 = 0
for i in range (len(prediction5)):
    if(prediction5[i]==y_test[i]):
        count5=count5+1

print(count5)
print(len(prediction5))
AccDT=accuracy_score(y_test,prediction5)*100
F1DT=f1_score(y_test,prediction5,average='weighted')*100
RDT=recall_score(y_test,prediction5,average='weighted')*100
PDT=precision_score(y_test,prediction5,average='weighted')*100

print('Confusion Matrix')
print(confusion_matrix(y_test, prediction5))

print("Accuracy : ",AccDT )

print ('f1 Score:',F1DT)

print ('Recall:',RDT)

print ('Precision:',PDT)

2077
2984
Confusion Matrix
[[   0    0    1    0    0]
 [   0    0    0    1    0]
 [   0    0 1056  458    0]
 [   0    0  446 1021    0]
 [   0    0    0    1    0]]
Accuracy :  69.60455764075067
f1 Score: 69.57109488303607
Recall: 69.60455764075067
Precision: 69.54011247146357


C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Tulan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
